### ISSUE TITLE
SEO optimizations (title, metadata, descriptions)

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/bestofui5-website#143]
Maybe adding some metadata information would be nice. For example the [open graph spec](https://ogp.me/) to make it look nice when the link to the page is being shared. Example https://github.com/wridgeu/github_pages/blob/da0f3fde5abf2266ea1198e46ac4a3e287780aae/src/index.html#L8-L15

What do you think @marianfoo? Too much? ^^

**Comment by marianfoo** [comment]
I don't think it's too much.
its a good idea
Feel free to create a PR for it
