### ISSUE TITLE
error occurred loading the font metadata for collection 'font-awesome-icons'

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/bestofui5-website#159]
![image](https://user-images.githubusercontent.com/13335743/165226180-b5ff992d-b354-4664-8df5-1b006a6bbb93.png)

**Comment by petermuessig** [comment]
The font-awesome-icons have been handled in the past by prettier. Maybe you should add them once again? Or maybe we can add them via the `ui5-tooling-modules`? 

This way, you can load a CSS resource or you could do the same for a JS resource to make them included in the bundle later on: 
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/f98c7211cca06cdcf74d051c182372a9186bba99/packages/ui5-app/webapp/tui-image-editor.html#L20

```js
sap.ui.require(["sap/ui/dom/includeStylesheet", "tui-image-editor"], function(includeStylesheet, TuiImageEditor) {
  includeStylesheet(sap.ui.require.toUrl("tui-image-editor/dist/tui-image-editor.css"));

  [...]
```
