### ISSUE TITLE
Allow to filter tooling extensions per GitHub repository

### ISSUE THREAD

**Issue by petermuessig** [ui5-community/bestofui5-website#213]
To be able to list all tooling extensions for the ui5-ecosystem-showcase or other mono repos we may add the possibility to filter by GitHub repository. WDYT?

**Comment by marianfoo** [comment]
Can we solve that by adding a additional tag?
You can name that how ever you like.
Seems to be the simplest solution

**Comment by marianfoo** [comment]
@petermuessig have a look at the PR if the solution is good to you
