### ISSUE TITLE
Build might fail

### ISSUE THREAD

**Issue by uxkjaer** [ui5-community/bestofui5-website#265]
I've made some changes in the showcase which might cause the build to fail. I'll fix with a pr later today.

**Comment by marianfoo** [comment]
It´s in a "try/catch", so build will likely not fail, but the parsing may fail for jsdoc

**Comment by uxkjaer** [comment]
Excellent, then I'm not too stressed 😂

**Comment by marianfoo** [comment]
yeah, no worries :D 
see here the code snippet
https://github.com/ui5-community/bestofui5-data/blob/0f85430b4837d6de747b22485c06230224ec3a1d/src/gh-repos.ts#L53-L57
