### ISSUE TITLE
Add framework versions for OpenUI5 and SAPUI5

### ISSUE THREAD

**Issue by petermuessig** [ui5-community/bestofui5-website#270]
In addition we should consider to add the metadata from OpenUI5 and SAPUI5 and list them in Best Of UI5:

* Framework: OpenUI5/SAPUI5
* Framework Versions
* List of Libraries

Metadata can be fetched from CDN (only supported versions) or from NPM:

* https://sdk.openui5.org/1.103.0/resources/sap-ui-version.json
* https://ui5.sap.com/1.103.0/resources/sap-ui-version.json

This should help to select a framework, the available version and the available libraries!

**Comment by marianfoo** [comment]
Sorry. I don't currently see the connection with BestOfUI5.
Should only the content of the JSON be visualized?
As I understand this requirements, this should be provided by SAP.

**Comment by petermuessig** [comment]
BestOfUI5 will be the central place of the metadata - but maybe this is something to discuss tomorrow during the evening event... 😄

**Comment by petermuessig** [comment]
I will re-consider this idea and we close the issue for now
