### ISSUE TITLE
Icon for `Library` is missing

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/bestofui5-website#281]
https://github.com/ui5-community/bestofui5-website/blob/a9ca7bc6b13d83740b35b9f09fef2be8fbc7ceb7/src/view/AllPackages.view.xml#L86-L93
![image](https://user-images.githubusercontent.com/13335743/179285240-2af2a86c-a064-43de-b427-646b2b6aeafc.png)

**Comment by marianfoo** [comment]
`<i class="fa-solid fa-book"></i>`

**Comment by petermuessig** [comment]
Use font awesome `book`

For type `binary` use font awesome `terminal`
