### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/bestofui5-website#59]
Similar to [bestofjs Timeline](https://bestofjs.org/timeline), create a timeline with the most recent updates on versions over all packages
Maybe even create a RSS Feed on the same data
Use the [UI5 Timeline Control](https://ui5.sap.com/#/entity/sap.suite.ui.commons.Timeline/sample/sap.suite.ui.commons.sample.Timeline) for this

**Comment by marianfoo** [comment]
timeline is not in openui5
better use web component https://sap.github.io/ui5-webcomponents/playground/components/Timeline/

**Comment by marianfoo** [comment]
@petermuessig 
Web Components Timeline seem to not work with dark mode currently
https://github.com/marianfoo/ui5-community.github.io/tree/add-timeline
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13335743/163712215-851a810c-d204-4a47-b0e6-10d98bf4e91f.png">
<img width="543" alt="image" src="https://user-images.githubusercontent.com/13335743/163712226-734050c5-b4db-41d7-8513-d04933ccbd5a.png">

**Comment by wridgeu** [comment]
> Web Components Timeline seem to not work with dark mode currently 

Hi @marianfoo 👋

I just wanted to drop some thoughts here. It seems to me that this is not yet officially a 'registered theme' for the Web Components(?) aka. the currently wrapped WebC is a bit behind and therefore does not support the `sap_horizon_dark` yet.

You won't find the `sap_horizon_dark` theme listed here
- https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/#theme
- or here https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/

Admittedly they can be found here (but this is the latest version iirc) https://github.com/SAP/openui5/tree/master/src/sap.ui.webc.fiori/src/sap/ui/webc/fiori/thirdparty/css/themes

Interesting Console warning ... 
![image](https://user-images.githubusercontent.com/14982812/163714493-3476842c-fe28-4906-a09c-238794e2f01c.png)
Themes.js
![image](https://user-images.githubusercontent.com/14982812/163714443-2370e232-7e7a-4e26-8b9e-9d73ca87198c.png)

*I guess the Web Components which are currently wrapped have a slightly older version?*

I drilled a bit down into the downloaded dependencies from the UI5 tooling and couldn't find the `sap_horizon_dark` theme here.
![image](https://user-images.githubusercontent.com/14982812/163714958-cc7f66d6-7f0a-4684-b1a6-44b145ee6438.png)

To get a bit more confident I installed it via npm myself `npm i @openui5/sap.ui.webc.fiori`
and found the same result.
![image](https://user-images.githubusercontent.com/14982812/163715178-874f1e54-adc5-4e84-9b44-7e6630a54ee6.png)
![image](https://user-images.githubusercontent.com/14982812/163715584-633b01ce-1e72-48b7-9617-49800abc5fc5.png)
 

It is already integrated with V.1.2.2 though https://github.com/SAP/ui5-webcomponents/blob/master/packages/base/CHANGELOG.md => https://github.com/SAP/ui5-webcomponents/compare/v1.2.1...v1.2.2

BR :)

**Comment by marianfoo** [comment]
Hey @wridgeu ,
thanks for confirming my assumption.
Seems like they updated it in the repo.
https://github.com/SAP/openui5/commits/master/src/sap.ui.webc.fiori/src/sap
But it´s not 1.2.x yet
https://github.com/SAP/openui5/blob/05f2723b507f1e3e70e1fe0c34038ad1c07be4d5/THIRDPARTY.txt#L432

I think alternative would be using horizon light or over npm.
Both options i don´t like.

Cheers

**Comment by wridgeu** [comment]
> https://github.com/SAP/openui5/blob/05f2723b507f1e3e70e1fe0c34038ad1c07be4d5/THIRDPARTY.txt#L432

Ah cool, I overlooked the `THIRDPARTY.txt` in the root folder. 😄 The alternatives don't seem too nice, you're right and manually doing some magic would probably be too "hacky". 😅

**Comment by marianfoo** [comment]
Works with OpenUI5 Version 1.101.0
opened PR with #127 
![image](https://user-images.githubusercontent.com/13335743/164056565-b90ffe39-87d0-40a5-890b-fd7204b4f3a6.png)
