### ISSUE TITLE
Improve the design of the website

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/bestofui5-website#7]
Maybe custom theme or just minimal CSS

**Comment by wridgeu** [comment]
Hey there,

the toolbar has a small "flaw" or maybe I'm just too picky. 😅 More specifically I'm talking about the slight rounded edge on each end of the toolbar. I don't have time for anything today so I'll just add this here or maybe this was intended - idk. ^^ 

![image](https://user-images.githubusercontent.com/14982812/162578899-00451d5f-0000-4807-85de-b505eff76449.png)

![image](https://user-images.githubusercontent.com/14982812/162578830-6fcdf3da-da1b-4433-8931-309d27e77425.png)

![image](https://user-images.githubusercontent.com/14982812/162578903-7a7e8ebf-b6be-4c32-9e33-566886728eb7.png)

It's probably not worth opening a new issue for and it kind of falls under the category of 'minimal css adjustments' and overall design improvements.

**Comment by marianfoo** [comment]
Is that the dark theme?
I might broke something because i can´t switch to dark anymore

**Comment by marianfoo** [comment]
@wridgeu 
you were right, fixed the error on dark theme (#69) and the small issue #70
you can review #70 if this fixes your issue 😀

**Comment by marianfoo** [comment]
Issue is too general, more specific problems with design require a separate issue
